In [2]:
import numpy as np
import pandas as pd
from collections import defaultdict as ddict

In [3]:
case_type = ('cases', 'infections')
region = 'Florida'
region_short = 'fl'
f_ground_truth = f'../data/usa/data_{case_type[0]}_fl.csv'

In [59]:
df_region = pd.read_csv(f_ground_truth, index_col='region').transpose()
df_region.index.set_names(['date'], inplace=True)
df_region.index = pd.to_datetime(df_region.index)
df_region = df_region.diff(axis=0)
print('Days = {}, Regions = {}'.format(*df_region.shape))
display(df_region.tail())

Days = 213, Regions = 67

region,"Alachua, Florida","Baker, Florida","Bay, Florida","Bradford, Florida","Brevard, Florida","Broward, Florida","Calhoun, Florida","Charlotte, Florida","Citrus, Florida","Clay, Florida",...,"St. Johns, Florida","St. Lucie, Florida","Sumter, Florida","Suwannee, Florida","Taylor, Florida","Union, Florida","Volusia, Florida","Wakulla, Florida","Walton, Florida","Washington, Florida"
date,,,,,,,,,,,,,,,,,,,,,
2020-08-16,39.0,1.0,13.0,5.0,26.0,391.0,2.0,9.0,18.0,21.0,...,9.0,25.0,19.0,7.0,5.0,0.0,28.0,8.0,7.0,4.0
2020-08-17,47.0,7.0,49.0,8.0,75.0,416.0,0.0,10.0,21.0,29.0,...,37.0,45.0,19.0,28.0,9.0,4.0,61.0,10.0,15.0,5.0
2020-08-18,49.0,4.0,55.0,7.0,51.0,356.0,5.0,22.0,11.0,22.0,...,15.0,56.0,19.0,8.0,4.0,6.0,63.0,5.0,18.0,20.0
2020-08-19,50.0,7.0,65.0,23.0,87.0,540.0,8.0,20.0,48.0,39.0,...,36.0,78.0,15.0,6.0,8.0,4.0,61.0,19.0,8.0,9.0
2020-08-20,50.0,9.0,53.0,5.0,45.0,505.0,14.0,28.0,19.0,33.0,...,31.0,81.0,52.0,21.0,18.0,10.0,90.0,12.0,13.0,6.0

In [72]:
def load_features(path):
    df = pd.read_csv(path, index_col='region')
    df = df.drop(columns=['type']).transpose()
    df.index.set_names(['date'], inplace=True)
    df.index = pd.to_datetime(df.index)
    return df

dfs = [
    ('wcli state', 'Florida', load_features('../data/usa/symptom-survey/fb-survey_smoothed_wcli-state.csv')),
    ('wcli county', None, load_features('../data/usa/symptom-survey/fb-survey_smoothed_wcli-county.csv')),
    ('cmnty cli state', 'Florida', load_features('../data/usa/symptom-survey/fb-survey_smoothed_hh_cmnty_cli-state.csv')),
    ('cmnty cli county', None, load_features('../data/usa/symptom-survey/fb-survey_smoothed_hh_cmnty_cli-county.csv')),
    ('doctor state', 'Florida', load_features('../data/usa/symptom-survey/doctor-visits_smoothed_adj_cli-state.csv')),
    ('doctor county', None, load_features('../data/usa/symptom-survey/doctor-visits_smoothed_adj_cli-county.csv')),
    ('test ratio', None, load_features('../data/usa/testing/ratio_features_county.csv')),
    ('test total', None, load_features('../data/usa/testing/total_features_county.csv')),
]
display(dfs[-2][2].tail())

region,"Autauga, Alabama","Baldwin, Alabama","Barbour, Alabama","Bibb, Alabama","Blount, Alabama","Bullock, Alabama","Butler, Alabama","Calhoun, Alabama","Chambers, Alabama","Cherokee, Alabama",...,"Niobrara, Wyoming","Park, Wyoming","Platte, Wyoming","Sheridan, Wyoming","Sublette, Wyoming","Sweetwater, Wyoming","Teton, Wyoming","Uinta, Wyoming","Washakie, Wyoming","Weston, Wyoming"
date,,,,,,,,,,,,,,,,,,,,,
2020-08-17,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,...,0.090,0.090,0.090,0.090,0.090,0.090,0.090,0.090,0.090,0.090
2020-08-18,0.077,0.077,0.077,0.077,0.077,0.077,0.077,0.077,0.077,0.077,...,0.081,0.081,0.081,0.081,0.081,0.081,0.081,0.081,0.081,0.081
2020-08-19,0.075,0.075,0.075,0.075,0.075,0.075,0.075,0.075,0.075,0.075,...,0.091,0.091,0.091,0.091,0.091,0.091,0.091,0.091,0.091,0.091
2020-08-20,0.073,0.073,0.073,0.073,0.073,0.073,0.073,0.073,0.073,0.073,...,0.076,0.076,0.076,0.076,0.076,0.076,0.076,0.076,0.076,0.076
2020-08-21,0.090,0.090,0.090,0.090,0.090,0.090,0.090,0.090,0.090,0.090,...,0.070,0.070,0.070,0.070,0.070,0.070,0.070,0.070,0.070,0.070

In [73]:
lagged = {}
lags = [0, 1, 3, 5, 7, 10, 14, 21, 28]
for lag in lags:
    corrs = ddict(list)
    for name, state, df in dfs:
        #df = df.diff(axis=0).fillna(0)
        for county in df_region.columns:
            query = county if state is None else state
            if query not in df.columns:
                corr = np.nan
            else:
                merged = pd.merge_asof(df_region[county], df[query].shift(lag), left_index=True, right_index=True)
                corr = merged.corr().iloc[0, 1]
            corrs[county].append(corr)
    corrs = [(k,) + tuple(v) for k, v in corrs.items()]
    df = pd.DataFrame(corrs, columns=['region'] + [n for n, _, _ in dfs])
    df.set_index('region', inplace=True)
    lagged[lag] = df.mean()
pd.DataFrame(lagged)

,0,1,3,5,7,10,14,21,28
wcli state,0.625115,0.620210,0.607027,0.593437,0.577318,0.543532,0.501886,0.370897,0.221690
wcli county,0.411608,0.407387,0.392653,0.381296,0.362523,0.324032,0.263340,0.154056,0.021236
cmnty cli state,0.614697,0.606743,0.588452,0.568160,0.543007,0.498150,0.428129,0.276580,0.119253
cmnty cli county,0.607112,0.599860,0.575033,0.548987,0.509064,0.452203,0.354121,0.185015,0.007786
doctor state,0.643618,0.652903,0.668999,0.670019,0.670705,0.673161,0.649234,0.588641,0.499202
doctor county,0.643422,0.646830,0.650956,0.647544,0.640483,0.625860,0.583149,0.485354,0.388848
test ratio,0.503146,0.501831,0.497414,0.490843,0.481625,0.461826,0.428580,0.354769,0.257138
test total,0.672501,0.672860,0.672300,0.671807,0.668250,0.660377,0.639571,0.593363,0.552041

##